# Generated by Django 4.2.4 on 2023-08-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messages',
            table='users_messages',
        ),
    ]
