# Generated by Django 4.2.4 on 2023-08-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(verbose_name=50)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('estate_name', models.CharField(max_length=50)),
                ('conditions', models.CharField(max_length=50)),
                ('utilities', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('pictures', models.CharField(max_length=200)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.address', verbose_name='property address')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertycategories', verbose_name='Property Category')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField()),
                ('attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.attributes', verbose_name='Property Attribute')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.properties', verbose_name='Property Name')),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertycategories', verbose_name='property category'),
        ),
        migrations.AddField(
            model_name='properties',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertytypes', verbose_name='property type'),
        ),
        migrations.AddField(
            model_name='properties',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='property owner'),
        ),
    ]
