# Generated by Django 4.2.4 on 2023-08-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='property_address',
        ),
        migrations.AlterModelTable(
            name='attributes',
            table='attributes',
        ),
        migrations.AlterModelTable(
            name='properties',
            table='properties',
        ),
        migrations.AlterModelTable(
            name='propertyattributes',
            table='property_attributes',
        ),
        migrations.AlterModelTable(
            name='propertycategories',
            table='property_categories',
        ),
        migrations.AlterModelTable(
            name='propertytypes',
            table='property_types',
        ),
    ]
