# Generated by Django 4.2.4 on 2023-08-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_address_table_alter_attributes_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='propertyattributes',
            old_name='attribute_id',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='propertyattributes',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='propertytypes',
            old_name='category_id',
            new_name='category',
        ),
    ]
