# Generated by Django 4.2.4 on 2023-08-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to='users.users', verbose_name='user id')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.properties', verbose_name='property id')),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_owner', to='users.users', verbose_name='user id')),
            ],
        ),
    ]
