# Generated by Django 4.2.4 on 2023-08-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='property_id',
            new_name='property',
        ),
    ]
